Added official Google Cloud instructions for building firebase on Cloud Build to ReadMe
GoogleCloudPlatform/cloud-builders-community pull request #453
Opened 2020-09-30 21:04 UTC by Robbie-Cook

This PR links these awesome instructions to the firebase builder: https://cloud.google.com/cloud-build/docs/deploying-builds/deploy-firebase

This link helps you to enable APIs more easily with those big blue button links :).

2020-09-30 21:09 UTC, Robbie-Cook commented
@googlebot I signed it!

2020-09-30 21:52 UTC, LOZORD approved these changes
Thanks for your contribution! I just have a few minor comments.

2020-09-30 21:52 UTC, LOZORD commented on firebase/README.md
> +
Nit: remove extra blank line?

2020-09-30 21:52 UTC, LOZORD commented on firebase/README.md
> +You can find official Google Cloud steps for this build processor [here](https://cloud.google.com/cloud-build/docs/deploying-builds/deploy-firebase).
Up to you: replace `steps` with something like `the official Google Cloud guide` just so people don't think these are just `Build.steps`?

2020-09-30 21:52 UTC, LOZORD commented on firebase/README.md
> +## Google Cloud Docs
Up to you: replace with `Official "Deploying to Firebase" Docs`?

2020-09-30 21:53 UTC, LOZORD commented
(I'll squash+merge your change once everything is resolved.)

2020-10-01 03:14 UTC, Robbie-Cook commented on firebase/README.md
> +
Whoops, will remove. Thank you!

2020-10-01 03:14 UTC, Robbie-Cook commented on firebase/README.md
> +You can find official Google Cloud steps for this build processor [here](https://cloud.google.com/cloud-build/docs/deploying-builds/deploy-firebase).
Great! Awesome suggestion, will do!

2020-10-01 03:14 UTC, Robbie-Cook commented on firebase/README.md
> +## Google Cloud Docs
Will do

2020-10-01 03:23 UTC, Robbie-Cook commented
Hey @LOZORD , have made those changes you suggested. Any more, let me know

2020-10-02 13:53 UTC, LOZORD requested changes

2020-10-02 13:53 UTC, LOZORD commented on firebase/README.md
> +#
Can you remove this unused `#` header please? Also it might be good to put the sentence with the link below the `This build step...` sentence.

2020-10-03 05:41 UTC, Robbie-Cook commented on firebase/README.md
> +#
Thank you. Have done @LOZORD

2020-10-03 05:42 UTC, Robbie-Cook commented
Have made those suggested changes @LOZORD :)

2020-10-05 14:14 UTC, LOZORD commented
Awesome, thanks again!

2020-10-05 14:14 UTC, LOZORD approved these changes

2020-10-05 14:14 UTC, merged

2020-10-05 21:16 UTC, Robbie-Cook commented
Thank you @LOZORD !